version: 2


build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

conda:
  environment: .pandoc_rtd_environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
